### ISSUE TITLE
test

### ISSUE THREAD

**Issue by rocketlaunchr-cto** [rocketlaunchr/igo#1]
test

**Comment by lucasalcantara** [comment]
by PayPal is fine by me. So I think we can make a deal and we can create the issues here. What do you think? and talk by whatsapp or slack or any other

**Comment by pjebs** [comment]
send me an email with your proposal: rocketlaunchr.cloud@gmail.com

**Comment by rocketlaunchr-cto** [comment]
send me an email with your proposal: rocketlaunchr.cloud@gmail.com

**Comment by lucasalcantara** [comment]
please, check your email.
